/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * RecentActivityRail — list of the most recent ~5 ecosystem events on the
 * home page. Consumes `/data/activity/feed.json` (stub for v1; a real feed
 * generated by `ecosystem-automation` is a follow-up — see open question in
 * `01-home-page.md`). Renders empty + loading + error states.
 */

import { ChevronRight } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

const FEED_URL = "/data/activity/feed.json";

type Stability = "stable" | "beta" | "alpha" | "deprecated" | "unmaintained" | "development";

interface ActivityItem {
  id: string;
  title: string;
  stability: Stability | "new";
  ecosystem: string;
  version: string | null;
  occurredAt: string;
  href: string;
}

interface FeedShape {
  generatedAt: string;
  items: ActivityItem[];
}

function formatRelative(occurredAt: string, now: Date = new Date()): string {
  const then = new Date(occurredAt);
  const diffMs = now.getTime() - then.getTime();
  if (Number.isNaN(diffMs) || diffMs < 0) return "just now";
  const diffDays = Math.floor(diffMs / 86_400_000);
  if (diffDays === 0) return "today";
  if (diffDays === 1) return "yesterday";
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 30) {
    const weeks = Math.floor(diffDays / 7);
    return `${weeks} week${weeks === 1 ? "" : "s"} ago`;
  }
  const months = Math.floor(diffDays / 30);
  return `${months} month${months === 1 ? "" : "s"} ago`;
}

function pillClass(stability: ActivityItem["stability"]): string {
  switch (stability) {
    case "stable":
    case "new":
      return "td-pill td-pill--stable";
    case "beta":
      return "td-pill td-pill--beta";
    case "alpha":
      return "td-pill td-pill--alpha";
    case "deprecated":
    case "unmaintained":
      return "td-pill td-pill--deprecated";
    default:
      return "td-pill td-pill--neutral";
  }
}

export interface RecentActivityRailProps {
  /** Max items to render. Default 5. */
  limit?: number;
  /** Override feed URL (mostly for tests). */
  feedUrl?: string;
}

export function RecentActivityRail({ limit = 5, feedUrl = FEED_URL }: RecentActivityRailProps) {
  const [items, setItems] = useState<ActivityItem[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const res = await fetch(feedUrl);
        if (!res.ok) throw new Error(`Feed responded with ${res.status}`);
        const data = (await res.json()) as FeedShape;
        if (cancelled) return;
        setItems(data.items.slice(0, limit));
      } catch (err) {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : String(err));
      }
    }
    load();
    return () => {
      cancelled = true;
    };
  }, [feedUrl, limit]);

  return (
    <div aria-labelledby="activity-title">
      <h3 id="activity-title" className="td-subsection-title">
        Recent activity
      </h3>
      <p className="td-subsection-lead">What changed in the last 30 days, across all ecosystems.</p>
      <div className="td-activity-card">
        {error ? (
          <p className="td-activity-empty" role="status">
            We couldn't load the activity feed right now. Check back soon.
          </p>
        ) : items === null ? (
          <p className="td-activity-loading" role="status" aria-live="polite">
            Loading recent activity…
          </p>
        ) : items.length === 0 ? (
          <p className="td-activity-empty">No recent activity to show.</p>
        ) : (
          <ul className="td-activity-list">
            {items.map((item) => (
              <li key={item.id} className="td-activity-item">
                <Link to={item.href} className="td-activity-link">
                  <span className={pillClass(item.stability)}>
                    {item.stability === "new" ? "new" : item.stability}
                  </span>
                  <div className="td-activity-body">
                    <div className="td-activity-title">{item.title}</div>
                    <span className="td-activity-meta">
                      {[item.ecosystem, item.version, formatRelative(item.occurredAt)]
                        .filter(Boolean)
                        .join(" · ")}
                    </span>
                  </div>
                  <ChevronRight className="td-activity-chevron" aria-hidden focusable="false" />
                </Link>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
