/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * RecentActivityRail — list of the most recent ~5 ecosystem events on the
 * home page. Consumes `/data/activity/feed.json` (stub for v1; a real feed
 * generated by `ecosystem-automation` is a follow-up — see open question in
 * `01-home-page.md`). Renders empty + loading + error states.
 */

import type { TFunction } from "i18next";
import { ChevronRight } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import { useActivityFeed, type ActivityStability } from "@/v1/hooks/use-activity-feed";

function formatRelative(occurredAt: string, t: TFunction<"home">, now: Date = new Date()): string {
  const then = new Date(occurredAt);
  const diffMs = now.getTime() - then.getTime();
  if (Number.isNaN(diffMs) || diffMs < 0) return t("homeV1.activity.relative.justNow");
  const diffDays = Math.floor(diffMs / 86_400_000);
  if (diffDays === 0) return t("homeV1.activity.relative.today");
  if (diffDays === 1) return t("homeV1.activity.relative.yesterday");
  if (diffDays < 7) return t("homeV1.activity.relative.daysAgo", { count: diffDays });
  if (diffDays < 30) {
    return t("homeV1.activity.relative.weeksAgo", { count: Math.floor(diffDays / 7) });
  }
  return t("homeV1.activity.relative.monthsAgo", { count: Math.floor(diffDays / 30) });
}

const PILL_VARIANT: Record<ActivityStability, string> = {
  stable: "td-pill--stable",
  new: "td-pill--stable",
  beta: "td-pill--beta",
  alpha: "td-pill--alpha",
  deprecated: "td-pill--deprecated",
  unmaintained: "td-pill--unmaintained",
  development: "td-pill--development",
};

function pillClass(stability: ActivityStability): string {
  return `td-pill ${PILL_VARIANT[stability]}`;
}

export interface RecentActivityRailProps {
  /** Max items to render. Default 5. */
  limit?: number;
  /** Override feed URL (mostly for tests). */
  feedUrl?: string;
}

export function RecentActivityRail({ limit = 5, feedUrl }: RecentActivityRailProps) {
  const { data: items, loading, error } = useActivityFeed({ feedUrl, limit });
  const { t } = useTranslation("home");

  return (
    <div aria-labelledby="activity-title">
      <h3 id="activity-title" className="td-subsection-title">
        {t("homeV1.activity.title")}
      </h3>
      <p className="td-subsection-lead">{t("homeV1.activity.lead")}</p>
      <div className="td-activity-card">
        {error ? (
          <p className="td-activity-empty" role="status">
            {t("homeV1.activity.error")}
          </p>
        ) : loading || items === null ? (
          <p className="td-activity-loading" role="status" aria-live="polite">
            {t("homeV1.activity.loading")}
          </p>
        ) : items.length === 0 ? (
          <p className="td-activity-empty">{t("homeV1.activity.empty")}</p>
        ) : (
          <ul className="td-activity-list">
            {items.map((item) => (
              <li key={item.id} className="td-activity-item">
                <Link to={item.href} className="td-activity-link">
                  <span className={pillClass(item.stability)}>
                    {t(`common:stability.${item.stability}`)}
                  </span>
                  <div className="td-activity-body">
                    <div className="td-activity-title">{item.title}</div>
                    <span className="td-activity-meta">
                      {[
                        // Feed ecosystems are free-form ids; unknown ones fall back to the raw id.
                        t(`homeV1.ecosystemNames.${item.ecosystem}`, {
                          defaultValue: item.ecosystem,
                        }),
                        item.version,
                        formatRelative(item.occurredAt, t),
                      ]
                        .filter(Boolean)
                        .join(" · ")}
                    </span>
                  </div>
                  <ChevronRight className="td-activity-chevron" aria-hidden focusable="false" />
                </Link>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
