/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { dump } from "js-yaml";
import type { ConfigNode } from "@/types/configuration";
import type {
  ConfigValue,
  ConfigValues,
  ConfigurationBuilderState,
} from "@/types/configuration-builder";
import { isPlainObject } from "./value-guards";

const EMPTY = Symbol("EMPTY");
type StrippedResult = ConfigValue | typeof EMPTY;

interface GenerateYamlOptions {
  header?: string;
  javaAgentVersion?: string;
}

function defaultHeader(schemaVersion: string, javaAgentVersion?: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const versionLine = javaAgentVersion
    ? `# Schema version: ${schemaVersion} - Java agent: ${javaAgentVersion}`
    : `# Schema version: ${schemaVersion}`;
  return [
    "# OpenTelemetry SDK Configuration",
    `# Generated by Ecosystem Explorer on ${date}`,
    versionLine,
    "#",
    "# Pass to the agent with:",
    "#   -Dotel.config.file=/path/to/otel-config.yaml",
    "#",
    "# NOTE: With the exception of env var substitution syntax (i.e. ${MY_ENV}),",
    "# SDKs ignore environment variables when interpreting config files.",
    "#",
    "# Schema docs: https://github.com/open-telemetry/opentelemetry-configuration/blob/main/schema-docs.md",
    "",
  ].join("\n");
}

function toFileFormatVersion(version: string): string {
  const m = version.match(/^(\d+)\.(\d+)/);
  return m ? `${m[1]}.${m[2]}` : version;
}

function emptiesToNull(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(emptiesToNull);
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return null;
    return Object.fromEntries(entries.map(([k, v]) => [k, emptiesToNull(v)]));
  }
  return value;
}

function dumpYaml(obj: unknown): string {
  const yaml = dump(emptiesToNull(obj), {
    sortKeys: true,
    lineWidth: -1,
    noRefs: true,
    quotingType: '"',
    styles: { "!!null": "empty" },
  });
  // js-yaml leaves a trailing space after the empty-style null representation.
  return yaml.replace(/: $/gm, ":");
}

function sectionComment(node: ConfigNode | undefined, fallbackKey: string): string {
  if (!node) return `# ${fallbackKey}\n`;
  const label = node.label ?? node.key;
  const desc = node.description?.trim();
  if (!desc) return `# ${label}\n`;
  if (desc.includes("\n")) {
    const lines = desc
      .split("\n")
      .map((l) => `# ${l.trim()}`)
      .filter((l) => l !== "# ");
    return `# ${label}\n${lines.join("\n")}\n`;
  }
  return `# ${label}: ${desc}\n`;
}

function stripEmpties(value: ConfigValue): StrippedResult {
  if (value === null || value === "") return EMPTY;
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return value;
  }

  if (Array.isArray(value)) {
    const kept: ConfigValue[] = [];
    for (const item of value) {
      const stripped = stripEmpties(item);
      if (stripped !== EMPTY) kept.push(stripped as ConfigValue);
    }
    return kept.length === 0 ? EMPTY : kept;
  }

  if (isPlainObject(value)) {
    const entries = Object.entries(value);
    if (entries.length === 1) {
      const childValue = entries[0][1];
      if (
        childValue === null ||
        (isPlainObject(childValue) && Object.keys(childValue).length === 0)
      ) {
        return value;
      }
    }
    const out: ConfigValues = {};
    for (const [k, v] of entries) {
      const stripped = stripEmpties(v);
      if (stripped !== EMPTY) out[k] = stripped as ConfigValue;
    }
    if (Object.keys(out).length === 0) {
      return EMPTY;
    }
    return out;
  }

  return EMPTY;
}

export function generateYaml(
  state: ConfigurationBuilderState,
  schema: ConfigNode,
  options?: GenerateYamlOptions
): string {
  const header = options?.header ?? defaultHeader(state.version, options?.javaAgentVersion);

  if (schema.controlType !== "group") {
    const parts = [header, "# Schema is not a group; cannot generate sections.", ""].filter(
      (p) => p !== ""
    );
    return parts.join("\n") + "\n";
  }

  const children = schema.children;

  const fileFormatBlock = dumpYaml({ file_format: toFileFormatVersion(state.version) });

  const others = children
    .filter((c) => c.key !== "file_format")
    .sort((a, b) => a.key.localeCompare(b.key));

  const sectionBlocks: string[] = [];
  for (const child of others) {
    if (child.controlType === "group") {
      if (state.enabledSections[child.key] !== true) continue;
      const raw = state.values[child.key];
      let stripped: StrippedResult = raw === undefined ? EMPTY : stripEmpties(raw);
      // Unwrap the plugin_select short-circuit at the section-body root: a
      // single-entry object with null value at the top level represents an
      // unset leaf, not a bare discriminator.
      if (stripped !== EMPTY && isPlainObject(stripped)) {
        const entries = Object.entries(stripped);
        if (entries.length === 1 && entries[0][1] === null) {
          stripped = EMPTY;
        }
      }
      const body = stripped === EMPTY ? {} : (stripped as ConfigValue);
      const block = sectionComment(child, child.key) + dumpYaml({ [child.key]: body });
      sectionBlocks.push(block);
      continue;
    }
    const raw = state.values[child.key];
    if (raw === undefined) continue;
    const stripped = stripEmpties(raw);
    if (stripped === EMPTY) continue;
    const block =
      sectionComment(child, child.key) + dumpYaml({ [child.key]: stripped as ConfigValue });
    sectionBlocks.push(block);
  }

  const parts = [header, fileFormatBlock, ...sectionBlocks].filter((p) => p !== "");
  return parts.join("\n") + "\n";
}
