/*
 * Copyright The OpenTelemetry Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { dump } from "js-yaml";
import type { ConfigNode } from "@/types/configuration";
import type {
  ConfigValue,
  ConfigValues,
  ConfigurationBuilderState,
} from "@/types/configuration-builder";
import { isPlainObject } from "./value-guards";

const EMPTY = Symbol("EMPTY");
type StrippedResult = ConfigValue | typeof EMPTY;

export type ConfigurationTarget = "javaagent" | "spring_starter";

interface GenerateYamlOptions {
  header?: string;
  javaAgentVersion?: string;
  /**
   * Output flavor. `"javaagent"` (default) emits a standalone declarative
   * config file. `"spring_starter"` wraps the body under a top-level `otel:`
   * key and renames `distribution.javaagent` → `distribution.spring_starter`
   * so the YAML can be pasted into a Spring Boot `application.yaml`.
   */
  target?: ConfigurationTarget;
}

function defaultHeader(
  schemaVersion: string,
  javaAgentVersion?: string,
  target: ConfigurationTarget = "javaagent"
): string {
  const date = new Date().toISOString().slice(0, 10);
  const versionLine = javaAgentVersion
    ? `# Schema version: ${schemaVersion} - Java agent: ${javaAgentVersion}`
    : `# Schema version: ${schemaVersion}`;
  if (target === "spring_starter") {
    // The Spring Boot starter consumes this YAML from application.yaml, not via
    // the agent's -Dotel.config.file flag, so the header carries spring-specific
    // usage. This is the durable copy of the guidance (it travels with the
    // copied/downloaded file); the on-screen hint is the short, clickable echo.
    return [
      "# OpenTelemetry Spring Boot starter configuration",
      `# Generated by Ecosystem Explorer on ${date}`,
      versionLine,
      "#",
      "# Paste at the top level of your Spring Boot application.yaml",
      "# (the otel: wrapper is already included).",
      "# Requires the OpenTelemetry Spring Boot starter >= 2.26.0.",
      "#",
      "# Docs: https://opentelemetry.io/docs/zero-code/java/spring-boot-starter/declarative-configuration/",
      "",
    ].join("\n");
  }
  return [
    "# OpenTelemetry SDK Configuration",
    `# Generated by Ecosystem Explorer on ${date}`,
    versionLine,
    "#",
    "# Pass to the agent with:",
    "#   -Dotel.config.file=/path/to/otel-config.yaml",
    "#",
    "# NOTE: With the exception of env var substitution syntax (i.e. ${MY_ENV}),",
    "# SDKs ignore environment variables when interpreting config files.",
    "#",
    "# Schema docs: https://github.com/open-telemetry/opentelemetry-configuration/blob/main/schema-docs.md",
    "",
  ].join("\n");
}

function toFileFormatVersion(version: string): string {
  const m = version.match(/^(\d+)\.(\d+)/);
  return m ? `${m[1]}.${m[2]}` : version;
}

function emptiesToNull(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(emptiesToNull);
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return null;
    return Object.fromEntries(entries.map(([k, v]) => [k, emptiesToNull(v)]));
  }
  return value;
}

function dumpYaml(obj: unknown): string {
  const yaml = dump(emptiesToNull(obj), {
    sortKeys: true,
    lineWidth: -1,
    noRefs: true,
    quotingType: '"',
    styles: { "!!null": "empty" },
  });
  // js-yaml leaves a trailing space after the empty-style null representation.
  return yaml.replace(/: $/gm, ":");
}

function sectionComment(node: ConfigNode | undefined, fallbackKey: string): string {
  if (!node) return `# ${fallbackKey}\n`;
  const label = node.label ?? node.key;
  const desc = node.description?.trim();
  if (!desc) return `# ${label}\n`;
  if (desc.includes("\n")) {
    const lines = desc
      .split("\n")
      .map((l) => `# ${l.trim()}`)
      .filter((l) => l !== "# ");
    return `# ${label}\n${lines.join("\n")}\n`;
  }
  return `# ${label}: ${desc}\n`;
}

function stripEmpties(value: ConfigValue): StrippedResult {
  if (value === null || value === "") return EMPTY;
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return value;
  }

  if (Array.isArray(value)) {
    const kept: ConfigValue[] = [];
    for (const item of value) {
      const stripped = stripEmpties(item);
      if (stripped !== EMPTY) kept.push(stripped as ConfigValue);
    }
    return kept.length === 0 ? EMPTY : kept;
  }

  if (isPlainObject(value)) {
    const entries = Object.entries(value);
    if (entries.length === 1) {
      const childValue = entries[0][1];
      if (
        childValue === null ||
        (isPlainObject(childValue) && Object.keys(childValue).length === 0)
      ) {
        return value;
      }
    }
    const out: ConfigValues = {};
    for (const [k, v] of entries) {
      const stripped = stripEmpties(v);
      if (stripped !== EMPTY) out[k] = stripped as ConfigValue;
    }
    if (Object.keys(out).length === 0) {
      return EMPTY;
    }
    return out;
  }

  return EMPTY;
}

export interface YamlSection {
  key: string;
  content: string;
}

export interface StructuredYaml {
  header: string;
  fileFormat: string;
  sections: YamlSection[];
}

// In spring_starter mode the state is still stored under
// `distribution.javaagent` (the canonical key the builder uses internally),
// but the Spring Boot starter reads its instrumentation config under
// `distribution.spring_starter`. Rename only at output time so toggling the
// target does not invalidate or duplicate state.
function renameJavaagentToSpringStarter(value: ConfigValue): ConfigValue {
  if (!isPlainObject(value)) return value;
  const out: ConfigValues = {};
  for (const [k, v] of Object.entries(value)) {
    out[k === "javaagent" ? "spring_starter" : k] = v;
  }
  return out;
}

// Spring's property placeholder resolver uses `${VAR:default}` (single colon)
// whereas the OpenTelemetry SDK declarative-config spec uses the shell-style
// `${VAR:-default}`. When users paste the explorer's YAML into Spring's
// `application.yaml`, Spring resolves placeholders first — and `${VAR:-default}`
// is not recognized, so the dash ends up in the value. Rewrite the syntax to
// Spring's form for the `spring_starter` target.
//
// Only the bare `${VAR:-default}` form is rewritten. SDK-prefixed forms like
// `${env:VAR:-default}` or `${sys:property:-default}` are left untouched: those
// carry semantics (env vs system property lookup) that have no Spring
// equivalent, so rewriting them would silently lose information.
function rewritePlaceholdersForSpring(text: string): string {
  return text.replace(/\$\{([A-Za-z_][A-Za-z0-9_]*):-/g, "${$1:");
}

function indentYamlBody(text: string, indent: string): string {
  if (text === "") return text;
  // Preserve a trailing newline so joined sections still separate cleanly.
  const trailing = text.endsWith("\n") ? "\n" : "";
  const body = trailing ? text.slice(0, -1) : text;
  const indented = body
    .split("\n")
    .map((line) => (line === "" ? line : indent + line))
    .join("\n");
  return indented + trailing;
}

export function generateYamlSections(
  state: ConfigurationBuilderState,
  schema: ConfigNode,
  options?: GenerateYamlOptions
): StructuredYaml {
  const target: ConfigurationTarget = options?.target ?? "javaagent";
  const isSpringStarter = target === "spring_starter";
  const header = options?.header ?? defaultHeader(state.version, options?.javaAgentVersion, target);

  if (schema.controlType !== "group") {
    const fallbackContent = "# Schema is not a group; cannot generate sections.\n";
    return {
      header,
      fileFormat: "",
      sections: [{ key: "error", content: fallbackContent }],
    };
  }

  const children = schema.children;
  const fileFormatVersion = toFileFormatVersion(state.version);
  const fileFormatBody = dumpYaml({ file_format: fileFormatVersion });
  const fileFormat = isSpringStarter
    ? `otel:\n${indentYamlBody(fileFormatBody, "  ")}`
    : fileFormatBody;

  const others = children
    .filter((c) => c.key !== "file_format")
    .sort((a, b) => a.key.localeCompare(b.key));

  const sections: YamlSection[] = [];
  for (const child of others) {
    if (child.controlType === "group") {
      if (state.enabledSections[child.key] !== true) continue;
      const raw = state.values[child.key];
      let stripped: StrippedResult = raw === undefined ? EMPTY : stripEmpties(raw);
      // Unwrap the plugin_select short-circuit at the section-body root: a
      // single-entry object with null value at the top level represents an
      // unset leaf, not a bare discriminator.
      if (stripped !== EMPTY && isPlainObject(stripped)) {
        const entries = Object.entries(stripped);
        if (entries.length === 1 && entries[0][1] === null) {
          stripped = EMPTY;
        }
      }
      let body: ConfigValue = stripped === EMPTY ? {} : (stripped as ConfigValue);
      if (isSpringStarter && child.key === "distribution") {
        body = renameJavaagentToSpringStarter(body);
      }
      const rawContent = sectionComment(child, child.key) + dumpYaml({ [child.key]: body });
      const indented = isSpringStarter ? indentYamlBody(rawContent, "  ") : rawContent;
      const content = isSpringStarter ? rewritePlaceholdersForSpring(indented) : indented;
      sections.push({ key: child.key, content });
      continue;
    }
    const raw = state.values[child.key];
    if (raw === undefined) continue;
    const stripped = stripEmpties(raw);
    if (stripped === EMPTY) continue;
    // `distribution` is a `key_value_map` in the real schema (not a group), so
    // it reaches this non-group branch. The javaagent→spring_starter rename
    // must happen here too, otherwise spring_starter output keeps the old key.
    let body: ConfigValue = stripped as ConfigValue;
    if (isSpringStarter && child.key === "distribution") {
      body = renameJavaagentToSpringStarter(body);
    }
    const rawContent = sectionComment(child, child.key) + dumpYaml({ [child.key]: body });
    const indented = isSpringStarter ? indentYamlBody(rawContent, "  ") : rawContent;
    const content = isSpringStarter ? rewritePlaceholdersForSpring(indented) : indented;
    sections.push({ key: child.key, content });
  }

  return {
    header,
    fileFormat,
    sections,
  };
}

export function structuredToString(structured: StructuredYaml): string {
  const parts = [
    structured.header,
    structured.fileFormat,
    ...structured.sections.map((s) => s.content),
  ].filter((p) => p !== "");
  return parts.join("\n") + "\n";
}

export function generateYaml(
  state: ConfigurationBuilderState,
  schema: ConfigNode,
  options?: GenerateYamlOptions
): string {
  return structuredToString(generateYamlSections(state, schema, options));
}
