name: DB Builder Integration Test

on:
  pull_request:
    paths:
      - "ecosystem-automation/explorer-db-builder/**"
      - "ecosystem-automation/watcher-common/**"
      - "ecosystem-registry/**"
      - "ecosystem-explorer/src/lib/api/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-db-integration:
    name: Integration test db-builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: ".python-version"

      - name: Install Python dependencies
        run: uv sync --locked --all-extras --dev

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: .bun-version
          cache: true
          cache-dependency-path: ecosystem-explorer/bun.lock

      - name: Install Bun dependencies
        run: bun install --frozen-lockfile
        working-directory: ecosystem-explorer

      - name: Build DB
        run: uv run explorer-db-builder --clean

      - name: Run integration tests
        run: bun run test:integration
        working-directory: ecosystem-explorer
